// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practice_web_apis.Data;

#nullable disable

namespace practice_web_apis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240810143719_initital")]
    partial class initital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("practice_web_apis.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc.",
                            Industry = "Technology",
                            LastDiv = 0.82m,
                            MarketCap = 2700000000000L,
                            Purchase = 150.75m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft Corporation",
                            Industry = "Technology",
                            LastDiv = 1.56m,
                            MarketCap = 2500000000000L,
                            Purchase = 310.10m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Tesla, Inc.",
                            Industry = "Automotive",
                            LastDiv = 0.00m,
                            MarketCap = 800000000000L,
                            Purchase = 650.25m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon.com, Inc.",
                            Industry = "E-commerce",
                            LastDiv = 0.00m,
                            MarketCap = 1600000000000L,
                            Purchase = 3300.50m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Alphabet Inc.",
                            Industry = "Technology",
                            LastDiv = 0.00m,
                            MarketCap = 1800000000000L,
                            Purchase = 2800.75m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Netflix, Inc.",
                            Industry = "Entertainment",
                            LastDiv = 0.00m,
                            MarketCap = 250000000000L,
                            Purchase = 550.00m,
                            Symbol = "NFLX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
